using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Media;

namespace VitorsWeeklyWorkTracking.Services;

public enum AppTheme
{
    ModernLight,
    PitchBlack,
    DarkSlate,
    MidnightNeon,
    CyberpunkSynthwave,
    MatrixTerminal,
    NordicFrost,
    EmeraldForest,
    SunsetGlow,
    CoffeeEspresso,
    CandyPop
}

public class ThemeOption
{
    public AppTheme Theme { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public string Icon { get; set; } = string.Empty;

    public override string ToString() => DisplayName;
}

public static class ThemeManager
{
    private static readonly string SettingsFilePath = Path.Combine(AppContext.BaseDirectory, "theme.json");
    private static AppTheme _currentTheme = AppTheme.ModernLight;

    public static AppTheme CurrentTheme => _currentTheme;
    public static event Action<AppTheme>? ThemeChanged;

    public static readonly IReadOnlyList<ThemeOption> AvailableThemes = new List<ThemeOption>
    {
        new() { Theme = AppTheme.ModernLight, DisplayName = "☀️ Modern Light", Icon = "☀️" },
        new() { Theme = AppTheme.PitchBlack, DisplayName = "🖤 Pitch Black (OLED)", Icon = "🖤" },
        new() { Theme = AppTheme.DarkSlate, DisplayName = "🌙 Dark Slate", Icon = "🌙" },
        new() { Theme = AppTheme.MidnightNeon, DisplayName = "🔮 Midnight Neon", Icon = "🔮" },
        new() { Theme = AppTheme.CyberpunkSynthwave, DisplayName = "⚡ Cyberpunk Synthwave", Icon = "⚡" },
        new() { Theme = AppTheme.MatrixTerminal, DisplayName = "💻 Matrix Terminal", Icon = "💻" },
        new() { Theme = AppTheme.NordicFrost, DisplayName = "❄️ Nordic Frost", Icon = "❄️" },
        new() { Theme = AppTheme.EmeraldForest, DisplayName = "🌲 Emerald Forest", Icon = "🌲" },
        new() { Theme = AppTheme.SunsetGlow, DisplayName = "🌅 Sunset Glow", Icon = "🌅" },
        new() { Theme = AppTheme.CoffeeEspresso, DisplayName = "☕ Warm Espresso", Icon = "☕" },
        new() { Theme = AppTheme.CandyPop, DisplayName = "🍬 Candy Pop", Icon = "🍬" }
    };

    public static void Initialize()
    {
        var savedTheme = LoadTheme();
        ApplyTheme(savedTheme, save: false);
    }

    public static void ApplyTheme(AppTheme theme, bool save = true)
    {
        _currentTheme = theme;
        var dict = Application.Current.Resources;

        var palette = GetPalette(theme);
        foreach (var (key, colorHex) in palette)
        {
            var brush = new SolidColorBrush((Color)ColorConverter.ConvertFromString(colorHex));
            brush.Freeze();
            dict[key] = brush;
        }

        if (save)
        {
            SaveTheme(theme);
        }

        ThemeChanged?.Invoke(theme);
    }

    private static Dictionary<string, string> GetPalette(AppTheme theme)
    {
        return theme switch
        {
            AppTheme.PitchBlack => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#000000",
                ["Theme.CardBackground"] = "#0A0A0A",
                ["Theme.CardBackgroundAlt"] = "#121212",
                ["Theme.CardBorder"] = "#27272A",
                ["Theme.CardHeaderBackground"] = "#141414",
                ["Theme.Foreground"] = "#FAFAFA",
                ["Theme.ForegroundMuted"] = "#A1A1AA",
                ["Theme.ForegroundSubtle"] = "#71717A",
                ["Theme.Primary"] = "#3B82F6",
                ["Theme.PrimaryHover"] = "#2563EB",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#18181B",
                ["Theme.SecondaryHover"] = "#27272A",
                ["Theme.SecondaryForeground"] = "#F4F4F5",
                ["Theme.SecondaryBorder"] = "#3F3F46",
                ["Theme.Success"] = "#10B981",
                ["Theme.SuccessHover"] = "#059669",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#EF4444",
                ["Theme.DangerHover"] = "#DC2626",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#F59E0B",
                ["Theme.Accent"] = "#60A5FA",
                ["Theme.InputBackground"] = "#0A0A0A",
                ["Theme.InputForeground"] = "#FAFAFA",
                ["Theme.InputBorder"] = "#27272A",
                ["Theme.InputBorderFocused"] = "#60A5FA",
                ["Theme.DataGridHeaderBackground"] = "#000000",
                ["Theme.DataGridHeaderForeground"] = "#E4E4E7",
                ["Theme.DataGridRowBackground"] = "#0A0A0A",
                ["Theme.DataGridAlternatingRowBackground"] = "#111111",
                ["Theme.DataGridRowHoverBackground"] = "#1F1F23",
                ["Theme.DataGridSelectionBackground"] = "#1E3A8A",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#222225",
                ["Theme.TabBackground"] = "#000000",
                ["Theme.TabSelectedBackground"] = "#0A0A0A",
                ["Theme.TabSelectedForeground"] = "#60A5FA",
                ["Theme.TabUnselectedForeground"] = "#A1A1AA",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#0C1E36",
                ["Theme.StatCard1Border"] = "#1D4ED8",
                ["Theme.StatCard1Text"] = "#60A5FA",
                ["Theme.StatCard1Title"] = "#93C5FD",
                ["Theme.StatCard2Bg"] = "#062E1F",
                ["Theme.StatCard2Border"] = "#059669",
                ["Theme.StatCard2Text"] = "#34D399",
                ["Theme.StatCard2Title"] = "#6EE7B7",
                ["Theme.StatCard3Bg"] = "#230E40",
                ["Theme.StatCard3Border"] = "#7C3AED",
                ["Theme.StatCard3Text"] = "#C084FC",
                ["Theme.StatCard3Title"] = "#DDD6FE",
                ["Theme.StatCard4Bg"] = "#361304",
                ["Theme.StatCard4Border"] = "#EA580C",
                ["Theme.StatCard4Text"] = "#FB923C",
                ["Theme.StatCard4Title"] = "#FED7AA",
                ["Theme.StatCard5Bg"] = "#062633",
                ["Theme.StatCard5Border"] = "#0891B2",
                ["Theme.StatCard5Text"] = "#22D3EE",
                ["Theme.StatCard5Title"] = "#A5F3FC",
            },

            AppTheme.DarkSlate => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#0F172A",
                ["Theme.CardBackground"] = "#1E293B",
                ["Theme.CardBackgroundAlt"] = "#182234",
                ["Theme.CardBorder"] = "#334155",
                ["Theme.CardHeaderBackground"] = "#243247",
                ["Theme.Foreground"] = "#F8FAFC",
                ["Theme.ForegroundMuted"] = "#94A3B8",
                ["Theme.ForegroundSubtle"] = "#64748B",
                ["Theme.Primary"] = "#0284C7",
                ["Theme.PrimaryHover"] = "#0369A1",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#273549",
                ["Theme.SecondaryHover"] = "#334155",
                ["Theme.SecondaryForeground"] = "#F1F5F9",
                ["Theme.SecondaryBorder"] = "#475569",
                ["Theme.Success"] = "#059669",
                ["Theme.SuccessHover"] = "#047857",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#E11D48",
                ["Theme.DangerHover"] = "#BE123C",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#D97706",
                ["Theme.Accent"] = "#38BDF8",
                ["Theme.InputBackground"] = "#0F172A",
                ["Theme.InputForeground"] = "#F8FAFC",
                ["Theme.InputBorder"] = "#334155",
                ["Theme.InputBorderFocused"] = "#38BDF8",
                ["Theme.DataGridHeaderBackground"] = "#0B1120",
                ["Theme.DataGridHeaderForeground"] = "#E2E8F0",
                ["Theme.DataGridRowBackground"] = "#1E293B",
                ["Theme.DataGridAlternatingRowBackground"] = "#172030",
                ["Theme.DataGridRowHoverBackground"] = "#2B3A50",
                ["Theme.DataGridSelectionBackground"] = "#0369A1",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#2A374A",
                ["Theme.TabBackground"] = "#0F172A",
                ["Theme.TabSelectedBackground"] = "#1E293B",
                ["Theme.TabSelectedForeground"] = "#38BDF8",
                ["Theme.TabUnselectedForeground"] = "#94A3B8",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#0C2B4E",
                ["Theme.StatCard1Border"] = "#0284C7",
                ["Theme.StatCard1Text"] = "#38BDF8",
                ["Theme.StatCard1Title"] = "#7DD3FC",
                ["Theme.StatCard2Bg"] = "#063728",
                ["Theme.StatCard2Border"] = "#059669",
                ["Theme.StatCard2Text"] = "#34D399",
                ["Theme.StatCard2Title"] = "#6EE7B7",
                ["Theme.StatCard3Bg"] = "#2D164D",
                ["Theme.StatCard3Border"] = "#7C3AED",
                ["Theme.StatCard3Text"] = "#C084FC",
                ["Theme.StatCard3Title"] = "#DDD6FE",
                ["Theme.StatCard4Bg"] = "#3B1C0B",
                ["Theme.StatCard4Border"] = "#EA580C",
                ["Theme.StatCard4Text"] = "#FB923C",
                ["Theme.StatCard4Title"] = "#FED7AA",
                ["Theme.StatCard5Bg"] = "#083344",
                ["Theme.StatCard5Border"] = "#0891B2",
                ["Theme.StatCard5Text"] = "#22D3EE",
                ["Theme.StatCard5Title"] = "#A5F3FC",
            },

            AppTheme.MidnightNeon => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#0D0B18",
                ["Theme.CardBackground"] = "#171329",
                ["Theme.CardBackgroundAlt"] = "#130F23",
                ["Theme.CardBorder"] = "#2E2452",
                ["Theme.CardHeaderBackground"] = "#211B3D",
                ["Theme.Foreground"] = "#F5F3FF",
                ["Theme.ForegroundMuted"] = "#A78BFA",
                ["Theme.ForegroundSubtle"] = "#6D5C9E",
                ["Theme.Primary"] = "#8B5CF6",
                ["Theme.PrimaryHover"] = "#7C3AED",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#241C42",
                ["Theme.SecondaryHover"] = "#32275C",
                ["Theme.SecondaryForeground"] = "#EDE9FE",
                ["Theme.SecondaryBorder"] = "#433575",
                ["Theme.Success"] = "#10B981",
                ["Theme.SuccessHover"] = "#059669",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#F43F5E",
                ["Theme.DangerHover"] = "#E11D48",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#F59E0B",
                ["Theme.Accent"] = "#06B6D4",
                ["Theme.InputBackground"] = "#100D21",
                ["Theme.InputForeground"] = "#F5F3FF",
                ["Theme.InputBorder"] = "#2E2554",
                ["Theme.InputBorderFocused"] = "#A855F7",
                ["Theme.DataGridHeaderBackground"] = "#0A0814",
                ["Theme.DataGridHeaderForeground"] = "#DDD6FE",
                ["Theme.DataGridRowBackground"] = "#171329",
                ["Theme.DataGridAlternatingRowBackground"] = "#130F22",
                ["Theme.DataGridRowHoverBackground"] = "#2B2150",
                ["Theme.DataGridSelectionBackground"] = "#6D28D9",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#281E48",
                ["Theme.TabBackground"] = "#0D0B18",
                ["Theme.TabSelectedBackground"] = "#171329",
                ["Theme.TabSelectedForeground"] = "#C084FC",
                ["Theme.TabUnselectedForeground"] = "#A78BFA",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#1E1B4B",
                ["Theme.StatCard1Border"] = "#6366F1",
                ["Theme.StatCard1Text"] = "#818CF8",
                ["Theme.StatCard1Title"] = "#C7D2FE",
                ["Theme.StatCard2Bg"] = "#064E3B",
                ["Theme.StatCard2Border"] = "#10B981",
                ["Theme.StatCard2Text"] = "#34D399",
                ["Theme.StatCard2Title"] = "#A7F3D0",
                ["Theme.StatCard3Bg"] = "#3B0764",
                ["Theme.StatCard3Border"] = "#A855F7",
                ["Theme.StatCard3Text"] = "#E879F9",
                ["Theme.StatCard3Title"] = "#F5D0FE",
                ["Theme.StatCard4Bg"] = "#431407",
                ["Theme.StatCard4Border"] = "#F97316",
                ["Theme.StatCard4Text"] = "#FB923C",
                ["Theme.StatCard4Title"] = "#FFEDD5",
                ["Theme.StatCard5Bg"] = "#164E63",
                ["Theme.StatCard5Border"] = "#06B6D4",
                ["Theme.StatCard5Text"] = "#67E8F9",
                ["Theme.StatCard5Title"] = "#CFFAFE",
            },

            AppTheme.CyberpunkSynthwave => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#0C0414",
                ["Theme.CardBackground"] = "#160826",
                ["Theme.CardBackgroundAlt"] = "#110520",
                ["Theme.CardBorder"] = "#421266",
                ["Theme.CardHeaderBackground"] = "#200B38",
                ["Theme.Foreground"] = "#FFF0FA",
                ["Theme.ForegroundMuted"] = "#F071D0",
                ["Theme.ForegroundSubtle"] = "#A242B8",
                ["Theme.Primary"] = "#FF007F",
                ["Theme.PrimaryHover"] = "#D6006B",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#250C42",
                ["Theme.SecondaryHover"] = "#36125E",
                ["Theme.SecondaryForeground"] = "#FCE7F3",
                ["Theme.SecondaryBorder"] = "#5B1C94",
                ["Theme.Success"] = "#00FFCC",
                ["Theme.SuccessHover"] = "#00D4AA",
                ["Theme.SuccessForeground"] = "#000000",
                ["Theme.Danger"] = "#FF0055",
                ["Theme.DangerHover"] = "#D60047",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#FFE600",
                ["Theme.Accent"] = "#00F0FF",
                ["Theme.InputBackground"] = "#10051C",
                ["Theme.InputForeground"] = "#FFF0FA",
                ["Theme.InputBorder"] = "#3E1061",
                ["Theme.InputBorderFocused"] = "#00F0FF",
                ["Theme.DataGridHeaderBackground"] = "#08020E",
                ["Theme.DataGridHeaderForeground"] = "#F5D0FE",
                ["Theme.DataGridRowBackground"] = "#160826",
                ["Theme.DataGridAlternatingRowBackground"] = "#10051E",
                ["Theme.DataGridRowHoverBackground"] = "#290D4A",
                ["Theme.DataGridSelectionBackground"] = "#7A1A9C",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#2E0C4F",
                ["Theme.TabBackground"] = "#0C0414",
                ["Theme.TabSelectedBackground"] = "#160826",
                ["Theme.TabSelectedForeground"] = "#00F0FF",
                ["Theme.TabUnselectedForeground"] = "#F071D0",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#1F0A42",
                ["Theme.StatCard1Border"] = "#7C3AED",
                ["Theme.StatCard1Text"] = "#C084FC",
                ["Theme.StatCard1Title"] = "#DDD6FE",
                ["Theme.StatCard2Bg"] = "#04332D",
                ["Theme.StatCard2Border"] = "#00FFCC",
                ["Theme.StatCard2Text"] = "#5EEAD4",
                ["Theme.StatCard2Title"] = "#99F6E4",
                ["Theme.StatCard3Bg"] = "#380628",
                ["Theme.StatCard3Border"] = "#FF007F",
                ["Theme.StatCard3Text"] = "#F472B6",
                ["Theme.StatCard3Title"] = "#FBCFE8",
                ["Theme.StatCard4Bg"] = "#3D2603",
                ["Theme.StatCard4Border"] = "#FFE600",
                ["Theme.StatCard4Text"] = "#FDE047",
                ["Theme.StatCard4Title"] = "#FEF08A",
                ["Theme.StatCard5Bg"] = "#042A38",
                ["Theme.StatCard5Border"] = "#00F0FF",
                ["Theme.StatCard5Text"] = "#67E8F9",
                ["Theme.StatCard5Title"] = "#A5F3FC",
            },

            AppTheme.MatrixTerminal => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#030804",
                ["Theme.CardBackground"] = "#071309",
                ["Theme.CardBackgroundAlt"] = "#050E07",
                ["Theme.CardBorder"] = "#103816",
                ["Theme.CardHeaderBackground"] = "#0B1E0E",
                ["Theme.Foreground"] = "#00FF66",
                ["Theme.ForegroundMuted"] = "#4ADE80",
                ["Theme.ForegroundSubtle"] = "#1E6B30",
                ["Theme.Primary"] = "#00DD55",
                ["Theme.PrimaryHover"] = "#00B844",
                ["Theme.PrimaryForeground"] = "#030804",
                ["Theme.Secondary"] = "#0C2411",
                ["Theme.SecondaryHover"] = "#13381B",
                ["Theme.SecondaryForeground"] = "#BBF7D0",
                ["Theme.SecondaryBorder"] = "#1B5226",
                ["Theme.Success"] = "#00FF66",
                ["Theme.SuccessHover"] = "#00DD55",
                ["Theme.SuccessForeground"] = "#030804",
                ["Theme.Danger"] = "#FF3344",
                ["Theme.DangerHover"] = "#CC1122",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#FACC15",
                ["Theme.Accent"] = "#39FF14",
                ["Theme.InputBackground"] = "#040D06",
                ["Theme.InputForeground"] = "#00FF66",
                ["Theme.InputBorder"] = "#103B16",
                ["Theme.InputBorderFocused"] = "#39FF14",
                ["Theme.DataGridHeaderBackground"] = "#020603",
                ["Theme.DataGridHeaderForeground"] = "#86EFAC",
                ["Theme.DataGridRowBackground"] = "#071309",
                ["Theme.DataGridAlternatingRowBackground"] = "#050E07",
                ["Theme.DataGridRowHoverBackground"] = "#0F2914",
                ["Theme.DataGridSelectionBackground"] = "#144A20",
                ["Theme.DataGridSelectionForeground"] = "#86EFAC",
                ["Theme.DataGridGridLines"] = "#0D2E13",
                ["Theme.TabBackground"] = "#030804",
                ["Theme.TabSelectedBackground"] = "#071309",
                ["Theme.TabSelectedForeground"] = "#39FF14",
                ["Theme.TabUnselectedForeground"] = "#4ADE80",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#052410",
                ["Theme.StatCard1Border"] = "#00DD55",
                ["Theme.StatCard1Text"] = "#4ADE80",
                ["Theme.StatCard1Title"] = "#86EFAC",
                ["Theme.StatCard2Bg"] = "#072E15",
                ["Theme.StatCard2Border"] = "#22C55E",
                ["Theme.StatCard2Text"] = "#6EE7B7",
                ["Theme.StatCard2Title"] = "#A7F3D0",
                ["Theme.StatCard3Bg"] = "#0C381C",
                ["Theme.StatCard3Border"] = "#10B981",
                ["Theme.StatCard3Text"] = "#34D399",
                ["Theme.StatCard3Title"] = "#D1FAE5",
                ["Theme.StatCard4Bg"] = "#2E2205",
                ["Theme.StatCard4Border"] = "#EAB308",
                ["Theme.StatCard4Text"] = "#FDE047",
                ["Theme.StatCard4Title"] = "#FEF08A",
                ["Theme.StatCard5Bg"] = "#052C28",
                ["Theme.StatCard5Border"] = "#14B8A6",
                ["Theme.StatCard5Text"] = "#5EEAD4",
                ["Theme.StatCard5Title"] = "#99F6E4",
            },

            AppTheme.NordicFrost => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#0A1128",
                ["Theme.CardBackground"] = "#141F3D",
                ["Theme.CardBackgroundAlt"] = "#0F1832",
                ["Theme.CardBorder"] = "#283C66",
                ["Theme.CardHeaderBackground"] = "#1B2A50",
                ["Theme.Foreground"] = "#F0F8FF",
                ["Theme.ForegroundMuted"] = "#80D8FF",
                ["Theme.ForegroundSubtle"] = "#4A7A9E",
                ["Theme.Primary"] = "#00B4D8",
                ["Theme.PrimaryHover"] = "#0096C7",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#1E2D4E",
                ["Theme.SecondaryHover"] = "#2A3E6B",
                ["Theme.SecondaryForeground"] = "#E0F7FA",
                ["Theme.SecondaryBorder"] = "#3A5485",
                ["Theme.Success"] = "#00E676",
                ["Theme.SuccessHover"] = "#00C853",
                ["Theme.SuccessForeground"] = "#000000",
                ["Theme.Danger"] = "#FF5252",
                ["Theme.DangerHover"] = "#FF1744",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#FFD740",
                ["Theme.Accent"] = "#40C4FF",
                ["Theme.InputBackground"] = "#0C162E",
                ["Theme.InputForeground"] = "#F0F8FF",
                ["Theme.InputBorder"] = "#283C66",
                ["Theme.InputBorderFocused"] = "#40C4FF",
                ["Theme.DataGridHeaderBackground"] = "#070C1E",
                ["Theme.DataGridHeaderForeground"] = "#B3E5FC",
                ["Theme.DataGridRowBackground"] = "#141F3D",
                ["Theme.DataGridAlternatingRowBackground"] = "#0F1832",
                ["Theme.DataGridRowHoverBackground"] = "#22335E",
                ["Theme.DataGridSelectionBackground"] = "#0077B6",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#1D2D52",
                ["Theme.TabBackground"] = "#0A1128",
                ["Theme.TabSelectedBackground"] = "#141F3D",
                ["Theme.TabSelectedForeground"] = "#40C4FF",
                ["Theme.TabUnselectedForeground"] = "#80D8FF",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#0B2847",
                ["Theme.StatCard1Border"] = "#00B4D8",
                ["Theme.StatCard1Text"] = "#38BDF8",
                ["Theme.StatCard1Title"] = "#BAE6FD",
                ["Theme.StatCard2Bg"] = "#06382E",
                ["Theme.StatCard2Border"] = "#00E676",
                ["Theme.StatCard2Text"] = "#69F0AE",
                ["Theme.StatCard2Title"] = "#B9F6CA",
                ["Theme.StatCard3Bg"] = "#1F1A4A",
                ["Theme.StatCard3Border"] = "#7C4DFF",
                ["Theme.StatCard3Text"] = "#B388FF",
                ["Theme.StatCard3Title"] = "#D1C4E9",
                ["Theme.StatCard4Bg"] = "#3D2E0A",
                ["Theme.StatCard4Border"] = "#FFD740",
                ["Theme.StatCard4Text"] = "#FFE57F",
                ["Theme.StatCard4Title"] = "#FFF8E1",
                ["Theme.StatCard5Bg"] = "#063544",
                ["Theme.StatCard5Border"] = "#00E5FF",
                ["Theme.StatCard5Text"] = "#84FFFF",
                ["Theme.StatCard5Title"] = "#E0F7FA",
            },

            AppTheme.EmeraldForest => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#081411",
                ["Theme.CardBackground"] = "#0E231E",
                ["Theme.CardBackgroundAlt"] = "#0B1D19",
                ["Theme.CardBorder"] = "#1B4036",
                ["Theme.CardHeaderBackground"] = "#14352D",
                ["Theme.Foreground"] = "#ECFDF5",
                ["Theme.ForegroundMuted"] = "#6EE7B7",
                ["Theme.ForegroundSubtle"] = "#347764",
                ["Theme.Primary"] = "#059669",
                ["Theme.PrimaryHover"] = "#047857",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#16382F",
                ["Theme.SecondaryHover"] = "#1E4C3F",
                ["Theme.SecondaryForeground"] = "#D1FAE5",
                ["Theme.SecondaryBorder"] = "#265C4E",
                ["Theme.Success"] = "#10B981",
                ["Theme.SuccessHover"] = "#059669",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#EF4444",
                ["Theme.DangerHover"] = "#DC2626",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#F59E0B",
                ["Theme.Accent"] = "#34D399",
                ["Theme.InputBackground"] = "#091B16",
                ["Theme.InputForeground"] = "#ECFDF5",
                ["Theme.InputBorder"] = "#1B4238",
                ["Theme.InputBorderFocused"] = "#10B981",
                ["Theme.DataGridHeaderBackground"] = "#06100E",
                ["Theme.DataGridHeaderForeground"] = "#A7F3D0",
                ["Theme.DataGridRowBackground"] = "#0E231E",
                ["Theme.DataGridAlternatingRowBackground"] = "#0B1D19",
                ["Theme.DataGridRowHoverBackground"] = "#1A453B",
                ["Theme.DataGridSelectionBackground"] = "#047857",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#193F35",
                ["Theme.TabBackground"] = "#081411",
                ["Theme.TabSelectedBackground"] = "#0E231E",
                ["Theme.TabSelectedForeground"] = "#34D399",
                ["Theme.TabUnselectedForeground"] = "#6EE7B7",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#0F3140",
                ["Theme.StatCard1Border"] = "#0284C7",
                ["Theme.StatCard1Text"] = "#38BDF8",
                ["Theme.StatCard1Title"] = "#BAE6FD",
                ["Theme.StatCard2Bg"] = "#064E3B",
                ["Theme.StatCard2Border"] = "#10B981",
                ["Theme.StatCard2Text"] = "#6EE7B7",
                ["Theme.StatCard2Title"] = "#D1FAE5",
                ["Theme.StatCard3Bg"] = "#2E1065",
                ["Theme.StatCard3Border"] = "#8B5CF6",
                ["Theme.StatCard3Text"] = "#C4B5FD",
                ["Theme.StatCard3Title"] = "#EDE9FE",
                ["Theme.StatCard4Bg"] = "#451A03",
                ["Theme.StatCard4Border"] = "#D97706",
                ["Theme.StatCard4Text"] = "#FCD34D",
                ["Theme.StatCard4Title"] = "#FEF3C7",
                ["Theme.StatCard5Bg"] = "#134E4A",
                ["Theme.StatCard5Border"] = "#14B8A6",
                ["Theme.StatCard5Text"] = "#5EEAD4",
                ["Theme.StatCard5Title"] = "#CCFBF1",
            },

            AppTheme.SunsetGlow => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#141211",
                ["Theme.CardBackground"] = "#1F1B19",
                ["Theme.CardBackgroundAlt"] = "#1A1614",
                ["Theme.CardBorder"] = "#39322D",
                ["Theme.CardHeaderBackground"] = "#2A2421",
                ["Theme.Foreground"] = "#FAFAF9",
                ["Theme.ForegroundMuted"] = "#D6D3D1",
                ["Theme.ForegroundSubtle"] = "#78716C",
                ["Theme.Primary"] = "#EA580C",
                ["Theme.PrimaryHover"] = "#C2410C",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#2F2824",
                ["Theme.SecondaryHover"] = "#3E3630",
                ["Theme.SecondaryForeground"] = "#F5F5F4",
                ["Theme.SecondaryBorder"] = "#4E423B",
                ["Theme.Success"] = "#16A34A",
                ["Theme.SuccessHover"] = "#15803D",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#DC2626",
                ["Theme.DangerHover"] = "#B91C1C",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#F59E0B",
                ["Theme.Accent"] = "#F97316",
                ["Theme.InputBackground"] = "#171413",
                ["Theme.InputForeground"] = "#FAFAF9",
                ["Theme.InputBorder"] = "#3A332E",
                ["Theme.InputBorderFocused"] = "#F97316",
                ["Theme.DataGridHeaderBackground"] = "#0E0C0B",
                ["Theme.DataGridHeaderForeground"] = "#E7E5E4",
                ["Theme.DataGridRowBackground"] = "#1F1B19",
                ["Theme.DataGridAlternatingRowBackground"] = "#191513",
                ["Theme.DataGridRowHoverBackground"] = "#3A312B",
                ["Theme.DataGridSelectionBackground"] = "#C2410C",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#332B25",
                ["Theme.TabBackground"] = "#141211",
                ["Theme.TabSelectedBackground"] = "#1F1B19",
                ["Theme.TabSelectedForeground"] = "#FB923C",
                ["Theme.TabUnselectedForeground"] = "#D6D3D1",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#1C2A3A",
                ["Theme.StatCard1Border"] = "#0284C7",
                ["Theme.StatCard1Text"] = "#7DD3FC",
                ["Theme.StatCard1Title"] = "#BAE6FD",
                ["Theme.StatCard2Bg"] = "#143522",
                ["Theme.StatCard2Border"] = "#16A34A",
                ["Theme.StatCard2Text"] = "#86EFAC",
                ["Theme.StatCard2Title"] = "#DCFCE7",
                ["Theme.StatCard3Bg"] = "#2E1B38",
                ["Theme.StatCard3Border"] = "#9333EA",
                ["Theme.StatCard3Text"] = "#D8B4FE",
                ["Theme.StatCard3Title"] = "#F3E8FF",
                ["Theme.StatCard4Bg"] = "#431407",
                ["Theme.StatCard4Border"] = "#EA580C",
                ["Theme.StatCard4Text"] = "#FDBA74",
                ["Theme.StatCard4Title"] = "#FFEDD5",
                ["Theme.StatCard5Bg"] = "#1C2E2A",
                ["Theme.StatCard5Border"] = "#0D9488",
                ["Theme.StatCard5Text"] = "#5EEAD4",
                ["Theme.StatCard5Title"] = "#CCFBF1",
            },

            AppTheme.CoffeeEspresso => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#17110C",
                ["Theme.CardBackground"] = "#241B14",
                ["Theme.CardBackgroundAlt"] = "#1C150F",
                ["Theme.CardBorder"] = "#423225",
                ["Theme.CardHeaderBackground"] = "#2E2219",
                ["Theme.Foreground"] = "#FAF4EC",
                ["Theme.ForegroundMuted"] = "#DDB892",
                ["Theme.ForegroundSubtle"] = "#A68A70",
                ["Theme.Primary"] = "#C97A3E",
                ["Theme.PrimaryHover"] = "#B0652D",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#33251C",
                ["Theme.SecondaryHover"] = "#423225",
                ["Theme.SecondaryForeground"] = "#EDE0D4",
                ["Theme.SecondaryBorder"] = "#5A4535",
                ["Theme.Success"] = "#588157",
                ["Theme.SuccessHover"] = "#3A5A40",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#BC4749",
                ["Theme.DangerHover"] = "#9B2226",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#E09F3E",
                ["Theme.Accent"] = "#E69138",
                ["Theme.InputBackground"] = "#1A130E",
                ["Theme.InputForeground"] = "#FAF4EC",
                ["Theme.InputBorder"] = "#423225",
                ["Theme.InputBorderFocused"] = "#E69138",
                ["Theme.DataGridHeaderBackground"] = "#100C08",
                ["Theme.DataGridHeaderForeground"] = "#E6CCB2",
                ["Theme.DataGridRowBackground"] = "#241B14",
                ["Theme.DataGridAlternatingRowBackground"] = "#1C150F",
                ["Theme.DataGridRowHoverBackground"] = "#36291F",
                ["Theme.DataGridSelectionBackground"] = "#7F4F24",
                ["Theme.DataGridSelectionForeground"] = "#FFFFFF",
                ["Theme.DataGridGridLines"] = "#33251B",
                ["Theme.TabBackground"] = "#17110C",
                ["Theme.TabSelectedBackground"] = "#241B14",
                ["Theme.TabSelectedForeground"] = "#E69138",
                ["Theme.TabUnselectedForeground"] = "#DDB892",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#382214",
                ["Theme.StatCard1Border"] = "#C97A3E",
                ["Theme.StatCard1Text"] = "#E69138",
                ["Theme.StatCard1Title"] = "#EDE0D4",
                ["Theme.StatCard2Bg"] = "#1C2E1D",
                ["Theme.StatCard2Border"] = "#588157",
                ["Theme.StatCard2Text"] = "#8FBC8F",
                ["Theme.StatCard2Title"] = "#D8E2DC",
                ["Theme.StatCard3Bg"] = "#331E2A",
                ["Theme.StatCard3Border"] = "#9C6680",
                ["Theme.StatCard3Text"] = "#D4A5B8",
                ["Theme.StatCard3Title"] = "#F3E6EC",
                ["Theme.StatCard4Bg"] = "#402A10",
                ["Theme.StatCard4Border"] = "#E09F3E",
                ["Theme.StatCard4Text"] = "#F4C584",
                ["Theme.StatCard4Title"] = "#FDF0DC",
                ["Theme.StatCard5Bg"] = "#1B3330",
                ["Theme.StatCard5Border"] = "#4D908E",
                ["Theme.StatCard5Text"] = "#90BE6D",
                ["Theme.StatCard5Title"] = "#E0ECE4",
            },

            AppTheme.CandyPop => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#FDF2F8",
                ["Theme.CardBackground"] = "#FFFFFF",
                ["Theme.CardBackgroundAlt"] = "#FCE7F3",
                ["Theme.CardBorder"] = "#FBCFE8",
                ["Theme.CardHeaderBackground"] = "#FDF4F9",
                ["Theme.Foreground"] = "#4A044E",
                ["Theme.ForegroundMuted"] = "#9D174D",
                ["Theme.ForegroundSubtle"] = "#BE185D",
                ["Theme.Primary"] = "#EC4899",
                ["Theme.PrimaryHover"] = "#DB2777",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#FCE7F3",
                ["Theme.SecondaryHover"] = "#FBCFE8",
                ["Theme.SecondaryForeground"] = "#831843",
                ["Theme.SecondaryBorder"] = "#F472B6",
                ["Theme.Success"] = "#10B981",
                ["Theme.SuccessHover"] = "#059669",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#F43F5E",
                ["Theme.DangerHover"] = "#E11D48",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#F59E0B",
                ["Theme.Accent"] = "#8B5CF6",
                ["Theme.InputBackground"] = "#FFFFFF",
                ["Theme.InputForeground"] = "#4A044E",
                ["Theme.InputBorder"] = "#F9A8D4",
                ["Theme.InputBorderFocused"] = "#EC4899",
                ["Theme.DataGridHeaderBackground"] = "#FDF2F8",
                ["Theme.DataGridHeaderForeground"] = "#831843",
                ["Theme.DataGridRowBackground"] = "#FFFFFF",
                ["Theme.DataGridAlternatingRowBackground"] = "#FDF2F8",
                ["Theme.DataGridRowHoverBackground"] = "#FCE7F3",
                ["Theme.DataGridSelectionBackground"] = "#FBCFE8",
                ["Theme.DataGridSelectionForeground"] = "#701A75",
                ["Theme.DataGridGridLines"] = "#FCE7F3",
                ["Theme.TabBackground"] = "#FCE7F3",
                ["Theme.TabSelectedBackground"] = "#FFFFFF",
                ["Theme.TabSelectedForeground"] = "#DB2777",
                ["Theme.TabUnselectedForeground"] = "#9D174D",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#FDF2F8",
                ["Theme.StatCard1Border"] = "#F472B6",
                ["Theme.StatCard1Text"] = "#DB2777",
                ["Theme.StatCard1Title"] = "#831843",
                ["Theme.StatCard2Bg"] = "#ECFDF5",
                ["Theme.StatCard2Border"] = "#6EE7B7",
                ["Theme.StatCard2Text"] = "#059669",
                ["Theme.StatCard2Title"] = "#065F46",
                ["Theme.StatCard3Bg"] = "#FAF5FF",
                ["Theme.StatCard3Border"] = "#C084FC",
                ["Theme.StatCard3Text"] = "#7C3AED",
                ["Theme.StatCard3Title"] = "#581C87",
                ["Theme.StatCard4Bg"] = "#FFFBEB",
                ["Theme.StatCard4Border"] = "#FCD34D",
                ["Theme.StatCard4Text"] = "#D97706",
                ["Theme.StatCard4Title"] = "#78350F",
                ["Theme.StatCard5Bg"] = "#F0FDFA",
                ["Theme.StatCard5Border"] = "#5EEAD4",
                ["Theme.StatCard5Text"] = "#0D9488",
                ["Theme.StatCard5Title"] = "#134E4A",
            },

            // Modern Light default
            _ => new Dictionary<string, string>
            {
                ["Theme.WindowBackground"] = "#F1F5F9",
                ["Theme.CardBackground"] = "#FFFFFF",
                ["Theme.CardBackgroundAlt"] = "#F8FAFC",
                ["Theme.CardBorder"] = "#E2E8F0",
                ["Theme.CardHeaderBackground"] = "#F8FAFC",
                ["Theme.Foreground"] = "#0F172A",
                ["Theme.ForegroundMuted"] = "#64748B",
                ["Theme.ForegroundSubtle"] = "#94A3B8",
                ["Theme.Primary"] = "#2563EB",
                ["Theme.PrimaryHover"] = "#1D4ED8",
                ["Theme.PrimaryForeground"] = "#FFFFFF",
                ["Theme.Secondary"] = "#F8FAFC",
                ["Theme.SecondaryHover"] = "#E2E8F0",
                ["Theme.SecondaryForeground"] = "#1E293B",
                ["Theme.SecondaryBorder"] = "#CBD5E1",
                ["Theme.Success"] = "#16A34A",
                ["Theme.SuccessHover"] = "#15803D",
                ["Theme.SuccessForeground"] = "#FFFFFF",
                ["Theme.Danger"] = "#DC2626",
                ["Theme.DangerHover"] = "#B91C1C",
                ["Theme.DangerForeground"] = "#FFFFFF",
                ["Theme.Warning"] = "#D97706",
                ["Theme.Accent"] = "#6366F1",
                ["Theme.InputBackground"] = "#FFFFFF",
                ["Theme.InputForeground"] = "#0F172A",
                ["Theme.InputBorder"] = "#CBD5E1",
                ["Theme.InputBorderFocused"] = "#2563EB",
                ["Theme.DataGridHeaderBackground"] = "#F1F5F9",
                ["Theme.DataGridHeaderForeground"] = "#334155",
                ["Theme.DataGridRowBackground"] = "#FFFFFF",
                ["Theme.DataGridAlternatingRowBackground"] = "#F8FAFC",
                ["Theme.DataGridRowHoverBackground"] = "#F1F5F9",
                ["Theme.DataGridSelectionBackground"] = "#DBEAFE",
                ["Theme.DataGridSelectionForeground"] = "#1E3A8A",
                ["Theme.DataGridGridLines"] = "#E2E8F0",
                ["Theme.TabBackground"] = "#E2E8F0",
                ["Theme.TabSelectedBackground"] = "#FFFFFF",
                ["Theme.TabSelectedForeground"] = "#2563EB",
                ["Theme.TabUnselectedForeground"] = "#64748B",
                // KPI Cards
                ["Theme.StatCard1Bg"] = "#EFF6FF",
                ["Theme.StatCard1Border"] = "#BFDBFE",
                ["Theme.StatCard1Text"] = "#1D4ED8",
                ["Theme.StatCard1Title"] = "#1E40AF",
                ["Theme.StatCard2Bg"] = "#F0FDF4",
                ["Theme.StatCard2Border"] = "#BBF7D0",
                ["Theme.StatCard2Text"] = "#15803D",
                ["Theme.StatCard2Title"] = "#166534",
                ["Theme.StatCard3Bg"] = "#FAF5FF",
                ["Theme.StatCard3Border"] = "#E9D5FF",
                ["Theme.StatCard3Text"] = "#7E22CE",
                ["Theme.StatCard3Title"] = "#6B21A8",
                ["Theme.StatCard4Bg"] = "#FFF7ED",
                ["Theme.StatCard4Border"] = "#FED7AA",
                ["Theme.StatCard4Text"] = "#C2410C",
                ["Theme.StatCard4Title"] = "#9A3412",
                ["Theme.StatCard5Bg"] = "#ECFEFF",
                ["Theme.StatCard5Border"] = "#A5F3FC",
                ["Theme.StatCard5Text"] = "#0E7490",
                ["Theme.StatCard5Title"] = "#155E75",
            }
        };
    }

    private static AppTheme LoadTheme()
    {
        try
        {
            if (File.Exists(SettingsFilePath))
            {
                var json = File.ReadAllText(SettingsFilePath);
                var doc = JsonDocument.Parse(json);
                if (doc.RootElement.TryGetProperty("Theme", out var themeProp))
                {
                    if (Enum.TryParse<AppTheme>(themeProp.GetString(), out var theme))
                    {
                        return theme;
                    }
                }
            }
        }
        catch
        {
            // Fallback to default on any deserialization failure
        }

        return AppTheme.ModernLight;
    }

    private static void SaveTheme(AppTheme theme)
    {
        try
        {
            var data = new { Theme = theme.ToString() };
            var json = JsonSerializer.Serialize(data, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(SettingsFilePath, json);
        }
        catch
        {
            // Silently ignore save errors
        }
    }
}
